### ISSUE TITLE
Display a leaderboard at the end

### ISSUE THREAD

**Issue by saikumar221** [saikumar221/Snake-Game#2]
Presently an alert is triggered with the highest score. Add an element to display the top 5 high scores.

**Comment by AprilShenk** [comment]
I would like to attempt this for hacktoberfest. Can you please assign it to me?

**Comment by saikumar221** [comment]
@AprilShenk Go for it and raise a PR directly when done.

**Comment by AprilShenk** [comment]
PR is in. Thank you!
